env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - plugin:react/jsx-runtime
overrides: []
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules: 
  react/jsx-filename-extensions:
    - 1
    - extensions:
      - *.js
      - *.jsx
  react/prop-types: 0
  react/destructuring-assignment:
    - 0
